# Generated by Django 4.1 on 2022-08-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='problem_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_code',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_stderr',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_stdout',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
