# Generated by Django 4.1 on 2022-08-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0002_submission_problem_name_alter_submission_user_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='problem_name',
        ),
    ]
