# Generated by Django 4.1 on 2022-09-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0004_alter_submission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('C++', 'C++'), ('C', 'C'), ('Python3', 'Python3'), ('Python2', 'Python2'), ('Java', 'Java')], default='C++', max_length=10),
        ),
    ]
