# Generated by Django 4.0.6 on 2022-08-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user_stderr',
            field=models.TextField(default='', max_length=1000000),
        ),
        migrations.AddField(
            model_name='submission',
            name='user_stdout',
            field=models.TextField(default='', max_length=1000000),
        ),
    ]
