# Generated by Django 4.0.6 on 2022-08-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0002_submission_user_stderr_submission_user_stdout'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='run_time',
            field=models.FloatField(default=0, null=True),
        ),
    ]
