# Generated by Django 4.0 on 2022-07-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='example',
        ),
    ]
