# Generated by Django 4.0 on 2022-07-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0002_remove_problem_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
