# Generated by Django 4.0 on 2022-07-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0003_remove_problem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
