# Generated by Django 4.0.6 on 2022-08-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0003_alter_testcase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='score',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solved_status',
        ),
    ]
