# Generated by Django 4.0 on 2022-07-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0004_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user_code',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OJ.problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OJ.user'),
        ),
        migrations.DeleteModel(
            name='Code',
        ),
    ]
