# Generated by Django 4.0.6 on 2022-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0004_remove_problem_score_remove_problem_solved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(default='Wrong Answer', max_length=100),
        ),
    ]
