# Generated by Django 4.0 on 2022-07-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0004_problem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='problem_id',
            new_name='problem',
        ),
    ]
