# Generated by Django 4.0 on 2022-07-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0005_rename_problem_id_submission_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
