# Generated by Django 4.0.6 on 2022-08-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0005_alter_submission_verdict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='solve_count',
            new_name='total_solve_count',
        ),
        migrations.AddField(
            model_name='user',
            name='easy_solve_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='medium_solve_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tough_solve_count',
            field=models.IntegerField(default=0),
        ),
    ]
