# Generated by Django 4.0 on 2022-07-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0005_submission_user_code_alter_submission_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('C++', 'C++'), ('C', 'C')], default='C++', max_length=10),
        ),
    ]
