# Generated by Django 4.0 on 2022-07-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0006_alter_submission_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
