# Generated by Django 4.0 on 2022-07-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0006_alter_submission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.CharField(max_length=1000000),
        ),
    ]
