# Generated by Django 4.0 on 2022-07-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0007_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solved_status',
            field=models.CharField(choices=[('Unsolved', 'Unsolved'), ('Solved', 'Solved')], default='', max_length=10),
        ),
    ]
