# Generated by Django 4.0 on 2022-07-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0007_alter_testcase_input_alter_testcase_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(),
        ),
    ]
