# Generated by Django 4.0 on 2022-07-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0009_alter_problem_difficulty_alter_problem_solved_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Firstname',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solved_status',
        ),
        migrations.AddField(
            model_name='user',
            name='Lastname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
