# Generated by Django 4.0 on 2022-07-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0010_rename_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
