# Generated by Django 4.0 on 2022-07-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0011_alter_testcase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sample_input',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_solution',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
