# Generated by Django 4.0 on 2022-07-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0012_problem_sample_input_problem_sample_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_solution',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_code',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(max_length=1000000),
        ),
    ]
