# Generated by Django 4.0 on 2022-07-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0013_alter_problem_description_alter_problem_sample_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='sample_input',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_output',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_solution',
        ),
        migrations.AddField(
            model_name='problem',
            name='example',
            field=models.TextField(default='', max_length=100000),
        ),
    ]
