# Generated by Django 4.0 on 2022-07-14 15:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0016_problem_solved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='rich_des',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
