# Generated by Django 4.0 on 2022-07-14 15:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0017_problem_rich_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='example',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='rich_des',
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
