# Generated by Django 4.0 on 2022-07-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0018_remove_problem_example_remove_problem_rich_des_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
