# Generated by Django 4.0 on 2022-07-15 17:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0019_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='example',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
