# Generated by Django 4.0 on 2022-07-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0020_problem_example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='time_stamp',
            new_name='submission_time',
        ),
    ]
