# Generated by Django 4.0 on 2022-07-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0021_rename_time_stamp_submission_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], max_length=10),
        ),
    ]
